from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / "file"
WINDOW_ICON_PATH = FILES_DIR / "calc.png"


# colors
PRIMARY_COLOR = "#1E81B0"
DARKER_PRIMARY_COLOR = "#16658A"
DARKEST_PRIMARY_COLOR = "#115270"

# Sizing
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 18
TEXT_MARGIN = 15
MINIMU_WIDTH = 500
